### Retrieve all groups created
GET http://localhost:8080/api/groups


### Create a new group using authenticated session
POST http://localhost:8080/api/groups
Content-Type: application/json

{
  "name": "Example Group",
  "description": "This is a sample group created using the HTTP Client."
}